import { env } from "cloudflare:workers";
import { and, desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { projectImages, projects, researchReferences } from "../../../db/schema";
import { apiError, requireAccountEmail } from "../../../lib/account";
type RuntimeEnv = { PROJECT_MEDIA?: R2Bucket; OPENAI_API_KEY?: string; OPENAI_MODEL?: string };
type StyleVariant = { id:"lifestyle"|"professional"|"minimal"; name:string; description:string; title:string; coverTitle:string; coverSubtitle:string; coverStyle?:Record<string,unknown>; body:string; tags:string[] };
type GeneratedDraft = { title:string; titleOptions?:string[]; coverTitle:string; coverSubtitle:string; coverStyle?:Record<string,unknown>; body:string; tags:string[]; highlights:string[]; riskNotes:string[]; coverIndex:number; mode:string; styleVariants?:StyleVariant[] };
function outputText(payload: Record<string, unknown>) { const output = Array.isArray(payload.output) ? payload.output : []; return output.flatMap((item) => { const content = item && typeof item === "object" && Array.isArray((item as {content?:unknown[]}).content) ? (item as {content:Array<{text?:string}>}).content : []; return content.map((part) => part.text || ""); }).join("\n"); }
function parseDraft(text: string): GeneratedDraft { const start=text.indexOf("{"); const end=text.lastIndexOf("}"); if(start<0||end<=start) throw new Error("AI 未返回可解析的文案"); return JSON.parse(text.slice(start,end+1)) as GeneratedDraft; }
export async function POST(request: Request) {
  try {
    const ownerEmail=await requireAccountEmail();
    const { projectId } = await request.json() as { projectId?: number }; if (!projectId) return Response.json({ error:"缺少项目编号" },{status:400});
    const runtime=env as unknown as RuntimeEnv; if(!runtime.PROJECT_MEDIA) throw new Error("项目图片存储暂不可用"); if(!runtime.OPENAI_API_KEY?.startsWith("sk-")) return Response.json({error:"AI 密钥尚未连接"},{status:503});
    const db=getDb(); const [project]=await db.select().from(projects).where(and(eq(projects.id,projectId),eq(projects.ownerEmail,ownerEmail))).limit(1); if(!project) return Response.json({error:"项目不存在"},{status:404});
    const images=await db.select().from(projectImages).where(eq(projectImages.projectId,projectId)); if(!images.length) return Response.json({error:"项目没有图片"},{status:400});
    const research=await db.select({copyAnalysis:researchReferences.copyAnalysis,coverAnalysis:researchReferences.coverAnalysis,audienceInsight:researchReferences.audienceInsight,reusablePattern:researchReferences.reusablePattern}).from(researchReferences).where(eq(researchReferences.ownerEmail,ownerEmail)).orderBy(desc(researchReferences.researchDate),desc(researchReferences.likes)).limit(3);
    const content:Array<Record<string,unknown>>=[{type:"input_text",text:"你是个人室内设计工作室的高级内容秘书。必须只依据上传的实景图生成小红书封面与原创文案。先识别空间类型、材质、灯光、动线、功能和画面情绪，再选择最适合封面的图片序号。项目名称、地址、面积、客户与介绍均为可选信息；缺失时直接省略，绝不能写‘待确认’或猜测。生成 3 套完整且差异明确的风格方案 styleVariants，id 依次为 lifestyle、professional、minimal，name 依次为‘松弛生活’、‘专业设计’、‘高级极简’。每套都必须包含 description、title、coverTitle、coverSubtitle、coverStyle、body、tags：松弛生活强调感受与共鸣，专业设计强调空间逻辑与方法，高级极简强调审美与留白。每套正文自然加入 3-6 个与语义相关的小表情图案，标题加入 1 个，不要连续堆叠。不得虚构地点、面积、客户身份、材料品牌或完工事实。必须使用最近3篇流量研究的抽象规律升级表达，但不得复制原句或版式。顶层 title、coverTitle、coverSubtitle、coverStyle、body、tags 使用 lifestyle 方案；titleOptions 使用三套方案各自的 title。coverStyle 规则：fontFamily 只能是 serif/sans/kai；颜色使用6位十六进制；overlayOpacity 为0-90；pattern 只能是 none/frame/grid/dots/corners；titleSize 为52-120；align 只能是 left/center；position 只能是 top/middle/bottom。只返回 JSON，字段为 title, titleOptions, coverTitle, coverSubtitle, coverStyle, body, tags, highlights, riskNotes, coverIndex, styleVariants。项目可选事实："+JSON.stringify(project)+"。近期研究规律（3篇）："+JSON.stringify(research)}];
    for(const image of images.sort((a,b)=>a.sortOrder-b.sortOrder).slice(0,10)){ const object=await runtime.PROJECT_MEDIA.get(image.objectKey); if(!object) continue; const bytes=new Uint8Array(await object.arrayBuffer()); let binary=""; for(let i=0;i<bytes.length;i+=0x8000) binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000)); content.push({type:"input_image",image_url:`data:${image.contentType};base64,${btoa(binary)}`,detail:"auto"}); }
    const apiResponse=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${runtime.OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:runtime.OPENAI_MODEL||"gpt-5.6-luna",input:[{role:"user",content}],max_output_tokens:2200})});
    if(!apiResponse.ok){if(apiResponse.status===401) throw new Error("AI 密钥无效或已失效"); throw new Error(`AI 服务暂不可用（${apiResponse.status}）`);} const responsePayload=await apiResponse.json() as Record<string,unknown>; const draft=parseDraft(outputText(responsePayload)); const variants=(Array.isArray(draft.styleVariants)?draft.styleVariants:[]).filter((item)=>item&&["lifestyle","professional","minimal"].includes(item.id)).slice(0,3); draft.styleVariants=variants; const options=(variants.length===3?variants.map((item)=>item.title):Array.isArray(draft.titleOptions)?draft.titleOptions:[]).map((item)=>String(item).trim()).filter(Boolean).slice(0,3); while(options.length<3) options.push(options.length===0?draft.title:`${draft.title}｜方案${options.length+1}`); draft.titleOptions=options; if(variants[0]){draft.title=variants[0].title;draft.coverTitle=variants[0].coverTitle;draft.coverSubtitle=variants[0].coverSubtitle;draft.coverStyle=variants[0].coverStyle;draft.body=variants[0].body;draft.tags=variants[0].tags;}else{draft.title=options[0];} draft.mode="AI 实景识别 · 3 种风格"; draft.coverIndex=Math.max(0,Number(draft.coverIndex||0)); await db.update(projects).set({status:"drafted",draftJson:JSON.stringify(draft)}).where(and(eq(projects.id,projectId),eq(projects.ownerEmail,ownerEmail))); return Response.json({draft});
  } catch(error){return apiError(error,"生成失败");}
}
